#include <DHT.h>
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/962d83b5-2f39-4d6a-ba97-2dca722424a4 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudTemperatureSensor tempH;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
const int DHTPIN = 32;
const int DHTTYPE = DHT11;
float temperatura = 0;

DHT dht(DHTPIN, DHTTYPE);

void setup() {
  // Inicia o monitor serial
  Serial.begin(9600);
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  // Inicia o sensor
  dht.begin();
}
// Inicia a leitura da temperatura
float lerTemperatura() {
  float temperature = dht.readTemperature();
  return temperature;
}

void loop() {
  // atualiza os dados no cloud
  ArduinoCloud.update();
  delay(1000);
  // Chama a variável criada no cloud para o envio das leituras do sensor
  temperatura = lerTemperatura();
  tempH = temperatura;
  // Imprime a temperatura
  Serial.print("Temperature (C): ");
  Serial.println(temperatura);
  // Your code here 
  
  
}
